global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090' # Prometheus monitorea a sí mismo
  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis:6379'
  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'tiktoc-db:5432'
  - job_name: 'elasticsearch'
    metrics_path: "/_cat/metrics"
    static_configs:
      - targets:
          - 'elasticsearch:9200'
  - job_name: 'redpanda'
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 'redpanda:9644'
